version: '3.8'

services:
    app:
        image: briansimpo/dolphinido
        container_name: dolphinido-app
        expose:
            - 8000
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        volumes:
            - storage:/var/www/html/storage
        networks:
            - dolphinido
        depends_on:
            - mysql
    
    mysql:
        image: mysql:8.0
        container_name: dolphinido-mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - dolphinido
    
    queue:
        image: briansimpo/dolphinido
        container_name: dolphinido-queue
        environment:
            - CONTAINER_ROLE=queue
        networks:
            - dolphinido
        depends_on:
            - mysql
            - app
    
    nginx:
        image: briansimpo/nginx
        container_name: dolphinido-nginx
        volumes:
            - storage:/var/www/html/storage
        ports:
            - 8080:8080
            - 443:443
        networks:
            - dolphinido
        depends_on:
            - app

networks:
    dolphinido:
        driver: bridge

volumes:
    storage:
        driver: local
    mysql:
        driver: local  