from .SongsController import SongsController
from .SongDownloadsController import SongDownloadsController
from .SongPlaysController import SongPlaysController
from .SongLikesController import SongLikesController
from .AlbumsController import AlbumsController
from .AlbumDownloadsController import AlbumDownloadsController
from .AlbumLikesController import AlbumLikesController
from .ArtistsController import ArtistsController
from .GenresController import GenresController
from .PlaylistsController import PlaylistsController
from .FollowingsController import FollowingsController

